"""
AI Models.

Data models for AI-generated insights, recommendations, conversations, and usage tracking.
"""
import uuid
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator


class AIRecommendation(models.Model):
    """
    AI-generated recommendation model.

    Stores personalized financial recommendations and insights
    generated by Claude AI.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='ai_recommendations'
    )

    # Recommendation type
    class RecommendationType(models.TextChoices):
        BUDGET_ALERT = 'budget_alert', 'Budget Alert'
        SPENDING_INSIGHT = 'spending_insight', 'Spending Insight'
        SAVING_TIP = 'saving_tip', 'Saving Tip'
        ANOMALY = 'anomaly', 'Anomaly Detection'

    type = models.CharField(
        max_length=50,
        choices=RecommendationType.choices,
        db_index=True,
        help_text="Type of recommendation"
    )

    # Content
    title = models.CharField(max_length=255)
    content = models.TextField()

    # Priority for display ordering (1-5 scale)
    PRIORITY_MAP = {
        'low': 1,
        'medium': 2,
        'high': 3,
        'urgent': 4,
        'critical': 5,
    }

    priority = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        default=3,
        db_index=True,
        help_text="Priority level (1=lowest, 5=highest)"
    )

    @classmethod
    def normalize_priority(cls, value):
        """Convert string priority to integer if needed."""
        if isinstance(value, str):
            return cls.PRIORITY_MAP.get(value.lower(), 3)
        if isinstance(value, int) and 1 <= value <= 5:
            return value
        return 3

    # Status
    is_read = models.BooleanField(default=False)
    is_dismissed = models.BooleanField(default=False)
    is_actionable = models.BooleanField(default=True)

    # Metadata
    metadata = models.JSONField(default=dict, blank=True)
    confidence_score = models.FloatField(null=True, blank=True)

    # Related entities (optional)
    related_transaction = models.ForeignKey(
        'transactions.Transaction',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='ai_recommendations'
    )
    related_category = models.ForeignKey(
        'transactions.TransactionCategory',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='ai_recommendations'
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    expires_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = 'AI recommendation'
        verbose_name_plural = 'AI recommendations'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'is_read']),
            models.Index(fields=['user', 'type']),
            models.Index(fields=['user', 'priority']),
            models.Index(fields=['user', 'created_at']),
        ]

    def __str__(self):
        return f"{self.title} ({self.type})"

    def mark_as_read(self):
        """Mark the recommendation as read."""
        if not self.is_read:
            self.is_read = True
            self.save(update_fields=['is_read', 'updated_at'])

    def dismiss(self):
        """Dismiss the recommendation."""
        self.is_dismissed = True
        self.save(update_fields=['is_dismissed', 'updated_at'])


class AICategorizationLog(models.Model):
    """
    Log of AI categorization attempts.

    Tracks categorization requests for analytics and improvement.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='ai_categorization_logs'
    )
    transaction = models.ForeignKey(
        'transactions.Transaction',
        on_delete=models.CASCADE,
        related_name='ai_categorization_logs'
    )

    # AI response
    suggested_category = models.ForeignKey(
        'transactions.TransactionCategory',
        on_delete=models.SET_NULL,
        null=True,
        related_name='ai_categorization_logs'
    )
    confidence_score = models.FloatField()
    reasoning = models.TextField(blank=True)

    # User feedback
    was_accepted = models.BooleanField(null=True)
    actual_category = models.ForeignKey(
        'transactions.TransactionCategory',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='ai_actual_categorizations'
    )

    # Metadata
    raw_response = models.JSONField(default=dict, blank=True)
    processing_time_ms = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'AI categorization log'
        verbose_name_plural = 'AI categorization logs'
        ordering = ['-created_at']

    def __str__(self):
        return f"Categorization for {self.transaction} - {self.confidence_score:.2f}"


class AIAnalysisCache(models.Model):
    """
    Cache for AI analysis results.

    Stores analysis results to reduce API calls for repeated queries.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='ai_analysis_cache'
    )

    # Cache key
    analysis_type = models.CharField(max_length=50)
    cache_key = models.CharField(max_length=255)

    # Cached data
    result = models.JSONField()

    # Expiration
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    class Meta:
        verbose_name = 'AI analysis cache'
        verbose_name_plural = 'AI analysis cache entries'
        unique_together = ['user', 'analysis_type', 'cache_key']
        indexes = [
            models.Index(fields=['user', 'analysis_type', 'cache_key']),
            models.Index(fields=['expires_at']),
        ]

    def __str__(self):
        return f"{self.analysis_type}: {self.cache_key}"

    @property
    def is_expired(self):
        """Check if cache entry has expired."""
        from django.utils import timezone
        return timezone.now() > self.expires_at


class AIConversation(models.Model):
    """
    AI conversation history with users.

    Stores the full conversation thread and context
    for the AI assistant feature.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for the conversation"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='ai_conversations',
        help_text="User who owns this conversation"
    )
    title = models.CharField(
        max_length=255,
        blank=True,
        default='',
        help_text="Optional title for the conversation"
    )
    messages = models.JSONField(
        default=list,
        help_text="List of messages in the conversation [{role, content, timestamp}]"
    )
    context = models.JSONField(
        default=dict,
        blank=True,
        help_text="Conversation context (user preferences, relevant data, etc.)"
    )
    is_active = models.BooleanField(
        default=True,
        db_index=True,
        help_text="Whether the conversation is still active"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When this conversation started"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="When this conversation was last updated"
    )

    class Meta:
        db_table = 'ai_conversations'
        ordering = ['-updated_at']
        indexes = [
            models.Index(fields=['user', 'is_active', '-updated_at']),
        ]
        verbose_name = 'AI Conversation'
        verbose_name_plural = 'AI Conversations'

    def __str__(self):
        return f"Conversation {self.id} - {self.user}"

    def add_message(self, role: str, content: str):
        """
        Add a message to the conversation.

        Args:
            role: 'user' or 'assistant'
            content: Message content
        """
        from django.utils import timezone

        message = {
            'role': role,
            'content': content,
            'timestamp': timezone.now().isoformat()
        }
        self.messages.append(message)
        self.save(update_fields=['messages', 'updated_at'])

    def get_messages_for_api(self):
        """
        Get messages formatted for the Claude API.

        Returns:
            List of messages with 'role' and 'content' keys
        """
        return [
            {'role': msg['role'], 'content': msg['content']}
            for msg in self.messages
        ]

    def clear_messages(self):
        """Clear all messages from the conversation."""
        self.messages = []
        self.save(update_fields=['messages', 'updated_at'])


class ChatSession(models.Model):
    """
    Chat session for the AI assistant.

    Groups related chat messages into a session.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='chat_sessions'
    )
    title = models.CharField(max_length=255, blank=True, default='')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']
        verbose_name = 'Chat Session'
        verbose_name_plural = 'Chat Sessions'

    def __str__(self):
        return f"Chat Session {self.id} - {self.user}"


class ChatMessage(models.Model):
    """
    Individual message in a chat session.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.ForeignKey(
        ChatSession,
        on_delete=models.CASCADE,
        related_name='messages'
    )
    role = models.CharField(max_length=20, choices=[('user', 'User'), ('assistant', 'Assistant')])
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']
        verbose_name = 'Chat Message'
        verbose_name_plural = 'Chat Messages'

    def __str__(self):
        return f"{self.role}: {self.content[:50]}"


class AIUsageLog(models.Model):
    """
    AI API usage logging for cost tracking.

    Tracks every API call to Claude for monitoring
    usage patterns and costs.
    """

    class ModelType(models.TextChoices):
        CLAUDE_3_OPUS = 'claude-3-opus-20240229', 'Claude 3 Opus'
        CLAUDE_3_SONNET = 'claude-3-sonnet-20240229', 'Claude 3 Sonnet'
        CLAUDE_3_HAIKU = 'claude-3-haiku-20240307', 'Claude 3 Haiku'
        CLAUDE_35_SONNET = 'claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'
        CLAUDE_35_HAIKU = 'claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'
        CLAUDE_4_OPUS = 'claude-opus-4-5-20251101', 'Claude Opus 4.5'

    class EndpointType(models.TextChoices):
        CHAT = 'chat', 'Chat'
        CATEGORIZE = 'categorize', 'Categorize'
        ANALYZE = 'analyze', 'Analyze Spending'
        RECOMMEND = 'recommend', 'Generate Recommendations'

    # Pricing per 1M tokens (as of late 2024)
    PRICING = {
        'claude-3-opus-20240229': {'input': 15.00, 'output': 75.00},
        'claude-3-sonnet-20240229': {'input': 3.00, 'output': 15.00},
        'claude-3-haiku-20240307': {'input': 0.25, 'output': 1.25},
        'claude-3-5-sonnet-20241022': {'input': 3.00, 'output': 15.00},
        'claude-3-5-haiku-20241022': {'input': 0.80, 'output': 4.00},
        'claude-opus-4-5-20251101': {'input': 15.00, 'output': 75.00},
    }

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for the log entry"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='ai_usage_logs',
        help_text="User who made this API call"
    )
    model = models.CharField(
        max_length=50,
        choices=ModelType.choices,
        db_index=True,
        help_text="AI model used"
    )
    tokens_input = models.PositiveIntegerField(
        default=0,
        help_text="Number of input tokens"
    )
    tokens_output = models.PositiveIntegerField(
        default=0,
        help_text="Number of output tokens"
    )
    cost_estimate = models.DecimalField(
        max_digits=10,
        decimal_places=6,
        default=0,
        help_text="Estimated cost in USD"
    )
    endpoint = models.CharField(
        max_length=20,
        choices=EndpointType.choices,
        db_index=True,
        help_text="API endpoint/feature used"
    )
    request_id = models.CharField(
        max_length=100,
        blank=True,
        default='',
        help_text="Claude API request ID for debugging"
    )
    latency_ms = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="API call latency in milliseconds"
    )
    success = models.BooleanField(
        default=True,
        db_index=True,
        help_text="Whether the API call was successful"
    )
    error_message = models.TextField(
        blank=True,
        default='',
        help_text="Error message if the call failed"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text="When this API call was made"
    )

    class Meta:
        db_table = 'ai_usage_logs'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'created_at']),
            models.Index(fields=['model', 'endpoint', 'created_at']),
        ]
        verbose_name = 'AI Usage Log'
        verbose_name_plural = 'AI Usage Logs'

    def __str__(self):
        return f"{self.endpoint} - {self.model} ({self.tokens_input + self.tokens_output} tokens)"

    def save(self, *args, **kwargs):
        """Calculate cost estimate before saving."""
        if self.model in self.PRICING:
            pricing = self.PRICING[self.model]
            input_cost = (self.tokens_input / 1_000_000) * pricing['input']
            output_cost = (self.tokens_output / 1_000_000) * pricing['output']
            self.cost_estimate = Decimal(str(input_cost + output_cost))
        super().save(*args, **kwargs)

    @classmethod
    def get_user_usage_stats(cls, user, days=30):
        """
        Get usage statistics for a user.

        Args:
            user: User instance
            days: Number of days to look back

        Returns:
            Dictionary with usage statistics
        """
        from django.utils import timezone
        from django.db.models import Sum, Count, Avg
        from datetime import timedelta

        start_date = timezone.now() - timedelta(days=days)

        stats = cls.objects.filter(
            user=user,
            created_at__gte=start_date,
            success=True
        ).aggregate(
            total_calls=Count('id'),
            total_input_tokens=Sum('tokens_input'),
            total_output_tokens=Sum('tokens_output'),
            total_cost=Sum('cost_estimate'),
            avg_latency=Avg('latency_ms')
        )

        return {
            'total_calls': stats['total_calls'] or 0,
            'total_input_tokens': stats['total_input_tokens'] or 0,
            'total_output_tokens': stats['total_output_tokens'] or 0,
            'total_tokens': (stats['total_input_tokens'] or 0) + (stats['total_output_tokens'] or 0),
            'total_cost': float(stats['total_cost'] or 0),
            'avg_latency_ms': stats['avg_latency'] or 0,
            'period_days': days
        }
