# Generated by Django 5.2.11 on 2026-02-04 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Base32 encoded secret key for TOTP", max_length=32
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Authenticator App",
                        help_text="User-friendly name for the device",
                        max_length=100,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the device has been verified by the user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_used_counter",
                    models.BigIntegerField(
                        default=-1,
                        help_text="Last successful counter to prevent replay attacks",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TOTP Device",
                "verbose_name_plural": "TOTP Devices",
            },
        ),
        migrations.CreateModel(
            name="BackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the backup code", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the code was used (null if unused)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Code",
                "verbose_name_plural": "Backup Codes",
                "indexes": [
                    models.Index(
                        fields=["user", "used_at"],
                        name="accounts_ba_user_id_019926_idx",
                    )
                ],
            },
        ),
    ]
