# Generated by Django 5.2.11 on 2026-02-04 22:41

import apps.banking.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("budget_insight", "Powens (Budget Insight)"),
                            ("truelayer", "TrueLayer"),
                            ("plaid", "Plaid"),
                        ],
                        max_length=50,
                    ),
                ),
                ("institution_id", models.CharField(max_length=255)),
                ("institution_name", models.CharField(max_length=255)),
                ("institution_logo_url", models.URLField(blank=True, null=True)),
                (
                    "_access_token_encrypted",
                    models.TextField(
                        blank=True, db_column="access_token_encrypted", null=True
                    ),
                ),
                (
                    "_refresh_token_encrypted",
                    models.TextField(
                        blank=True, db_column="refresh_token_encrypted", null=True
                    ),
                ),
                (
                    "provider_connection_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("consent_expires_at", models.DateTimeField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=50)),
                ("sync_error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "bank connection",
                "verbose_name_plural": "bank connections",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, apps.banking.models.EncryptedFieldMixin),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_account_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("official_name", models.CharField(blank=True, max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("credit", "Credit Card"),
                            ("loan", "Loan"),
                            ("investment", "Investment"),
                            ("mortgage", "Mortgage"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("account_subtype", models.CharField(blank=True, max_length=100)),
                ("account_number_masked", models.CharField(blank=True, max_length=50)),
                ("iban_masked", models.CharField(blank=True, max_length=50)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                            ("GBP", "British Pound"),
                            ("CHF", "Swiss Franc"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("custom_name", models.CharField(blank=True, max_length=255)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("balance_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="banking.bankconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "bank account",
                "verbose_name_plural": "bank accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Sync"),
                            ("incremental", "Incremental"),
                            ("balance", "Balance Only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accounts_synced", models.IntegerField(default=0)),
                ("transactions_synced", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="banking.bankconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync log",
                "verbose_name_plural": "sync logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(
                fields=["user", "status"], name="banking_ban_user_id_539e2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(
                fields=["provider", "status"], name="banking_ban_provide_69a700_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankconnection",
            unique_together={("user", "provider", "institution_id")},
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["user", "account_type"], name="banking_ban_user_id_47a347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["user", "is_hidden"], name="banking_ban_user_id_5f74b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankaccount",
            unique_together={("connection", "provider_account_id")},
        ),
    ]
