# Generated by Django 5.2.11 on 2026-02-04 22:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=255)),
                (
                    "server_version",
                    models.JSONField(help_text="Data as it exists on the server"),
                ),
                ("client_version", models.JSONField(help_text="Data from the client")),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("server_wins", "Server Version Kept"),
                            ("client_wins", "Client Version Kept"),
                            ("merged", "Merged"),
                            ("manual", "Manual Resolution"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolved_version", models.JSONField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conflicting_device_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sync conflict",
                "verbose_name_plural": "sync conflicts",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "resolution_status"],
                        name="sync_syncco_user_id_3c3dc9_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="sync_syncco_model_n_29121d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("push", "Client to Server"),
                            ("pull", "Server to Client"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("items_pushed", models.PositiveIntegerField(default=0)),
                ("items_pulled", models.PositiveIntegerField(default=0)),
                ("items_failed", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_timestamp", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_details", models.JSONField(blank=True, null=True)),
                ("sync_metadata", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sync log",
                "verbose_name_plural": "sync logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at"],
                        name="sync_synclo_user_id_47f6b5_idx",
                    ),
                    models.Index(
                        fields=["device_id", "-started_at"],
                        name="sync_synclo_device__b4f28c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="sync_synclo_status_bff9a9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(help_text="The data to be synced")),
                (
                    "client_timestamp",
                    models.DateTimeField(
                        help_text="Timestamp when the change was made on the client"
                    ),
                ),
                (
                    "server_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the change was received on the server",
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Normal"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=2,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("max_retries", models.PositiveSmallIntegerField(default=3)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "source_device_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_conflict", models.BooleanField(default=False)),
                ("conflict_resolution", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sync queue item",
                "verbose_name_plural": "sync queue items",
                "ordering": ["-priority", "client_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_processed"],
                        name="sync_syncqu_user_id_0a7860_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="sync_syncqu_model_n_ef1342_idx",
                    ),
                    models.Index(
                        fields=["-priority", "client_timestamp"],
                        name="sync_syncqu_priorit_494fb6_idx",
                    ),
                ],
            },
        ),
    ]
