"""
Pecunia Desktop Pages Module

Contains all page/view components for the application.
"""

from .dashboard import (
    DashboardPage,
    SyncStatus,
    SummaryCard,
    QuickActionButton,
    RecentTransactionItem,
    SyncStatusIndicator,
    BudgetProgressItem,
    ChartPlaceholder,
)
from .dashboard_widgets import (
    BalanceWidget,
    RecentTransactionsWidget,
    BudgetProgressWidget,
    QuickActionsWidget,
    SyncStatusWidget,
    AIInsightsWidget,
    DashboardWidgetContainer,
    DraggableWidget,
    WidgetSize,
)
from .transactions import (
    TransactionsPage,
    TransactionListPage,
    TransactionTableModel,
    TransactionFilterProxyModel,
    TransactionFilter,
    Transaction,
    TransactionType,
    SyncStatus as TransactionSyncStatus,
    FilterPanel,
    SummaryBar,
    BulkActionsBar,
    PaginationWidget,
)
from .transaction_detail import (
    TransactionDetailDialog,
    Attachment,
    HistoryEntry,
    HistoryTimeline,
    AttachmentsPanel,
    RelatedTransactionsWidget,
)
from .transaction_form import (
    TransactionFormDialog,
    TypeSelector,
    AmountInputField,
    CategoryInputField,
    DateInputField,
    AccountInputField,
    TagsInputField,
    NotesInputField,
)
from .transaction_import import (
    TransactionImportWizard,
    ImportResult,
    ImportedTransaction,
    ColumnMapping,
    FileFormat,
    FileDropZone,
)
from .budgets import (
    BudgetsPage,
    BudgetListPage,
    BudgetDetailPage,
    BudgetFormPage,
    BudgetCard,
    BudgetSummaryWidget,
    BudgetItemProgressBar,
    BudgetVsActualChart,
    BudgetDistributionChart,
    BudgetPeriod,
    BudgetStatus,
)
from .budget_detail import (
    BudgetDetailPage as EnhancedBudgetDetailPage,
    BudgetHeaderCard,
    BudgetItemsTable,
    TransactionsListWidget,
    CategoryBreakdownChart,
    SpendingTrendChart,
    AnimatedProgressBar,
)
from .budget_wizard import (
    BudgetWizardDialog,
    GeneralInfoPage,
    CategoryAllocationPage,
    AlertsConfigPage,
    ReviewPage,
)
from .budget_item_editor import (
    BudgetItemEditor,
    BudgetItemEditorDialog,
    BudgetItemsList,
    CategorySelector,
    AmountInput,
    AlertThresholdSlider,
    BudgetItemPreview,
)
from .settings import (
    SettingsPage,
    CategoriesTab,
    RegionalTab,
    PrivacyTab,
    CategoryDialog,
)
from .settings_sections import (
    AccountSection,
    AppearanceSection,
    SyncSection,
    NotificationsSection,
    SubscriptionSection,
    DataSection,
    AboutSection,
    ThemePreviewWidget,
    TwoFactorDialog,
)
from .login import LoginPage, RegisterPage, ForgotPasswordPage, AuthContainer
from .banking import (
    BankingPage,
    BankAccountCard,
    TotalBalanceCard,
    EmptyStateWidget,
    ConnectionStatus as BankConnectionStatus,
    create_banking_page,
)
from .bank_connect import (
    BankConnectWizard,
    InstitutionSearchWidget,
    OAuthConnectWidget,
    AccountSelectionWidget,
    ConfirmationWidget,
    SearchInstitutionPage,
    OAuthPage,
    SelectAccountsPage,
    ConfirmationPage,
    InstitutionInfo,
    AccountInfo,
    WizardStep,
    create_bank_connect_wizard,
)
from .bank_account_detail import (
    BankAccountDetailDialog,
    AccountInfoWidget,
    RecentTransactionsWidget as AccountTransactionsWidget,
    SyncHistoryWidget,
    AccountDetails,
    TransactionItem,
    SyncHistoryItem,
    ConnectionStatus as AccountConnectionStatus,
    create_account_detail_dialog,
    create_mock_account_details,
    create_mock_transactions,
    create_mock_sync_history,
)
from .sync_status import (
    SyncStatusWidget as BankSyncStatusWidget,
    SyncStatusBar,
    SyncStatusIndicator as BankSyncStatusIndicator,
    SyncDetailsWidget,
    SyncErrorWidget,
    AnimatedProgressBar as SyncAnimatedProgressBar,
    SyncState,
    SyncProgress,
    SyncError,
    create_sync_status_widget,
    create_sync_status_bar,
)

__all__ = [
    # Dashboard
    'DashboardPage',
    'SyncStatus',
    'SummaryCard',
    'QuickActionButton',
    'RecentTransactionItem',
    'SyncStatusIndicator',
    'BudgetProgressItem',
    'ChartPlaceholder',
    # Dashboard Widgets
    'BalanceWidget',
    'RecentTransactionsWidget',
    'BudgetProgressWidget',
    'QuickActionsWidget',
    'SyncStatusWidget',
    'AIInsightsWidget',
    'DashboardWidgetContainer',
    'DraggableWidget',
    'WidgetSize',
    # Transactions - Main Page
    'TransactionsPage',
    'TransactionListPage',
    'TransactionTableModel',
    'TransactionFilterProxyModel',
    'TransactionFilter',
    'Transaction',
    'TransactionType',
    'TransactionSyncStatus',
    'FilterPanel',
    'SummaryBar',
    'BulkActionsBar',
    'PaginationWidget',
    # Transactions - Detail Dialog
    'TransactionDetailDialog',
    'Attachment',
    'HistoryEntry',
    'HistoryTimeline',
    'AttachmentsPanel',
    'RelatedTransactionsWidget',
    # Transactions - Form Dialog
    'TransactionFormDialog',
    'TypeSelector',
    'AmountInputField',
    'CategoryInputField',
    'DateInputField',
    'AccountInputField',
    'TagsInputField',
    'NotesInputField',
    # Transactions - Import Wizard
    'TransactionImportWizard',
    'ImportResult',
    'ImportedTransaction',
    'ColumnMapping',
    'FileFormat',
    'FileDropZone',
    # Budgets - Core
    'BudgetsPage',
    'BudgetListPage',
    'BudgetDetailPage',
    'BudgetFormPage',
    'BudgetCard',
    'BudgetSummaryWidget',
    'BudgetItemProgressBar',
    'BudgetVsActualChart',
    'BudgetDistributionChart',
    'BudgetPeriod',
    'BudgetStatus',
    # Budgets - Enhanced Detail
    'EnhancedBudgetDetailPage',
    'BudgetHeaderCard',
    'BudgetItemsTable',
    'TransactionsListWidget',
    'CategoryBreakdownChart',
    'SpendingTrendChart',
    'AnimatedProgressBar',
    # Budgets - Wizard
    'BudgetWizardDialog',
    'GeneralInfoPage',
    'CategoryAllocationPage',
    'AlertsConfigPage',
    'ReviewPage',
    # Budgets - Item Editor
    'BudgetItemEditor',
    'BudgetItemEditorDialog',
    'BudgetItemsList',
    'CategorySelector',
    'AmountInput',
    'AlertThresholdSlider',
    'BudgetItemPreview',
    # Settings - Main Page
    'SettingsPage',
    'CategoriesTab',
    'RegionalTab',
    'PrivacyTab',
    'CategoryDialog',
    # Settings - Sections
    'AccountSection',
    'AppearanceSection',
    'SyncSection',
    'NotificationsSection',
    'SubscriptionSection',
    'DataSection',
    'AboutSection',
    'ThemePreviewWidget',
    'TwoFactorDialog',
    # Auth
    'LoginPage',
    'RegisterPage',
    'ForgotPasswordPage',
    'AuthContainer',
    # Banking - Main Page
    'BankingPage',
    'BankAccountCard',
    'TotalBalanceCard',
    'EmptyStateWidget',
    'BankConnectionStatus',
    'create_banking_page',
    # Banking - Connect Wizard
    'BankConnectWizard',
    'InstitutionSearchWidget',
    'OAuthConnectWidget',
    'AccountSelectionWidget',
    'ConfirmationWidget',
    'SearchInstitutionPage',
    'OAuthPage',
    'SelectAccountsPage',
    'ConfirmationPage',
    'InstitutionInfo',
    'AccountInfo',
    'WizardStep',
    'create_bank_connect_wizard',
    # Banking - Account Detail
    'BankAccountDetailDialog',
    'AccountInfoWidget',
    'AccountTransactionsWidget',
    'SyncHistoryWidget',
    'AccountDetails',
    'TransactionItem',
    'SyncHistoryItem',
    'AccountConnectionStatus',
    'create_account_detail_dialog',
    'create_mock_account_details',
    'create_mock_transactions',
    'create_mock_sync_history',
    # Banking - Sync Status
    'BankSyncStatusWidget',
    'SyncStatusBar',
    'BankSyncStatusIndicator',
    'SyncDetailsWidget',
    'SyncErrorWidget',
    'SyncAnimatedProgressBar',
    'SyncState',
    'SyncProgress',
    'SyncError',
    'create_sync_status_widget',
    'create_sync_status_bar',
]
