# Generated by Django 5.2.11 on 2026-02-04 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICategorizationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("reasoning", models.TextField(blank=True)),
                ("was_accepted", models.BooleanField(null=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actual_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_actual_categorizations",
                        to="transactions.transactioncategory",
                    ),
                ),
                (
                    "suggested_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_categorization_logs",
                        to="transactions.transactioncategory",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_categorization_logs",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_categorization_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI categorization log",
                "verbose_name_plural": "AI categorization logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysisCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("analysis_type", models.CharField(max_length=50)),
                ("cache_key", models.CharField(max_length=255)),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI analysis cache",
                "verbose_name_plural": "AI analysis cache entries",
                "indexes": [
                    models.Index(
                        fields=["user", "analysis_type", "cache_key"],
                        name="ai_aianalys_user_id_b45245_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="ai_aianalys_expires_dc1291_idx"
                    ),
                ],
                "unique_together": {("user", "analysis_type", "cache_key")},
            },
        ),
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the conversation",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional title for the conversation",
                        max_length=255,
                    ),
                ),
                (
                    "messages",
                    models.JSONField(
                        default=list,
                        help_text="List of messages in the conversation [{role, content, timestamp}]",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conversation context (user preferences, relevant data, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the conversation is still active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this conversation started"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this conversation was last updated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Conversation",
                "verbose_name_plural": "AI Conversations",
                "db_table": "ai_conversations",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "-updated_at"],
                        name="ai_conversa_user_id_5c3a43_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("budget_alert", "Budget Alert"),
                            ("spending_insight", "Spending Insight"),
                            ("saving_tip", "Saving Tip"),
                            ("anomaly", "Anomaly Detection"),
                        ],
                        db_index=True,
                        help_text="Type of recommendation",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=3,
                        help_text="Priority level (1=lowest, 5=highest)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("is_actionable", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommendations",
                        to="transactions.transactioncategory",
                    ),
                ),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommendations",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI recommendation",
                "verbose_name_plural": "AI recommendations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="ai_airecomm_user_id_9ded3c_idx",
                    ),
                    models.Index(
                        fields=["user", "type"], name="ai_airecomm_user_id_669fd6_idx"
                    ),
                    models.Index(
                        fields=["user", "priority"],
                        name="ai_airecomm_user_id_8ae4e4_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_airecomm_user_id_ac5f76_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the log entry",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("claude-3-opus-20240229", "Claude 3 Opus"),
                            ("claude-3-sonnet-20240229", "Claude 3 Sonnet"),
                            ("claude-3-haiku-20240307", "Claude 3 Haiku"),
                            ("claude-3-5-sonnet-20241022", "Claude 3.5 Sonnet"),
                            ("claude-3-5-haiku-20241022", "Claude 3.5 Haiku"),
                            ("claude-opus-4-5-20251101", "Claude Opus 4.5"),
                        ],
                        db_index=True,
                        help_text="AI model used",
                        max_length=50,
                    ),
                ),
                (
                    "tokens_input",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of input tokens"
                    ),
                ),
                (
                    "tokens_output",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of output tokens"
                    ),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated cost in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("categorize", "Categorize"),
                            ("analyze", "Analyze Spending"),
                            ("recommend", "Generate Recommendations"),
                        ],
                        db_index=True,
                        help_text="API endpoint/feature used",
                        max_length=20,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Claude API request ID for debugging",
                        max_length=100,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="API call latency in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the API call was successful",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the call failed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this API call was made",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made this API call",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
                "db_table": "ai_usage_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_usage_lo_user_id_3f9263_idx",
                    ),
                    models.Index(
                        fields=["model", "endpoint", "created_at"],
                        name="ai_usage_lo_model_db39c2_idx",
                    ),
                ],
            },
        ),
    ]
