# Generated by Django 5.2.11 on 2026-02-04 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the plan (e.g., 'Professional', 'Enterprise')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the plan",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("pro", "Professional"),
                            ("business", "Business"),
                        ],
                        default="free",
                        help_text="Subscription tier level",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of the plan"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        help_text="Three-letter ISO currency code",
                        max_length=3,
                    ),
                ),
                (
                    "stripe_price_id_monthly",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Price ID for monthly billing (e.g., 'price_xxx')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stripe_price_id_yearly",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Price ID for yearly billing (e.g., 'price_xxx')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly price in the default currency",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Yearly price in the default currency",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features included in this plan (e.g., ['AI categorization', 'Bank sync', 'Priority support'])",
                    ),
                ),
                (
                    "limits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Usage limits for this plan (e.g., {'accounts': 5, 'transactions_per_month': 1000, 'budgets': 10})",
                    ),
                ),
                ("max_bank_accounts", models.PositiveIntegerField(default=1)),
                ("max_budgets", models.PositiveIntegerField(default=3)),
                (
                    "max_transactions_per_month",
                    models.PositiveIntegerField(default=100),
                ),
                ("max_categories", models.PositiveIntegerField(default=10)),
                ("max_family_members", models.PositiveIntegerField(default=0)),
                ("ai_categorization", models.BooleanField(default=False)),
                ("ai_insights", models.BooleanField(default=False)),
                ("export_csv", models.BooleanField(default=True)),
                ("export_pdf", models.BooleanField(default=False)),
                ("bank_sync", models.BooleanField(default=False)),
                ("recurring_transactions", models.BooleanField(default=False)),
                ("custom_categories", models.BooleanField(default=False)),
                ("budget_alerts", models.BooleanField(default=False)),
                ("multi_currency", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
                ("api_access", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is available for new subscriptions",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which plans are displayed (lower = first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["display_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Subscription ID (e.g., 'sub_xxx')",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Customer ID (e.g., 'cus_xxx')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("trialing", "Trialing"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("unpaid", "Unpaid"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the current billing period",
                        null=True,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the current billing period",
                        null=True,
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the subscription will cancel at the end of the period",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscription was canceled",
                        null=True,
                    ),
                ),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("status", models.CharField(default="open", max_length=20)),
                (
                    "invoice_pdf_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "hosted_invoice_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "stripe_event_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Event",
                "verbose_name_plural": "Subscription Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe PaymentIntent ID (e.g., 'pi_xxx')",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Invoice ID (e.g., 'in_xxx')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Charge ID (e.g., 'ch_xxx')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Three-letter ISO currency code (e.g., 'USD', 'EUR')",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the payment"
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of payment method (e.g., 'card', 'bank_transfer')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "payment_method_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of card or account",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "payment_method_brand",
                    models.CharField(
                        blank=True,
                        help_text="Card brand (e.g., 'visa', 'mastercard')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("refund_reason", models.TextField(blank=True)),
                (
                    "invoice_pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to download the invoice PDF",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "hosted_invoice_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to view the hosted invoice",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment History",
                "verbose_name_plural": "Payment Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="subscriptio_user_id_86b406_idx",
                    ),
                    models.Index(
                        fields=["status"], name="subscriptio_status_7ff7df_idx"
                    ),
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="subscriptio_stripe__716b84_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="subscriptio_status_5e8870_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="subscriptio_stripe__12aa53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_customer_id"], name="subscriptio_stripe__3277e4_idx"
            ),
        ),
    ]
